### ISSUE TITLE
适应新数据格式

### ISSUE THREAD

**Issue by PEFT2026** [ridiculouz/LLMaAA#2]
作者 您好，
看到您的工作后，我也想把自己的数据用您的办法去生成新的数据，但是在操作过程中，出现了点问题，在readme文档中，看到如果想要适应新数据的话，要为新数据集创建名为config_{dataset}.json的配置文件，用于指定标注器和生成器的参数。这个配置文件是要怎么去配置呢？如果我只想要训练进行产生新的数据，我是否应该修改代码，不用去划分测试集呢？望解答，谢谢

**Comment by ridiculouz** [comment]
您好，
此处指的是`~/src/llm_annototor/configs/`和`~/src/data_synth/configs/`下的配置文件，它们指定了prompt的模板。可以参考别的数据集的json配置实现。
