### ISSUE TITLE
Running the scripts break due to relative imports of packages

### ISSUE THREAD

**Issue by joao-luz** [ridiculouz/LLMaAA#3]
When trying to run your code I get tons of `ImportError: attempted relative import with no known parent package` and some `ImportError: attempted relative import beyond top-level package`. It even happens on the `demo_retrieval.py` script. I'm able to fix this by removing the "." before internal import such as `from .similarity.embedding import get_embeddings, get_cosine_similarity`, but end up running into similar problems with other files.

I may be able to refactor the code to import the files the right way, but I'm curious as to how **you** run these files? Or, at least, what was the intended way to run them? Do I go to `src/` and add the current path as a package in python? Do I do this from the base path? I'm puzzled as to how you'd upload the code if just running it runs into import errors..

**Comment by ridiculouz** [comment]
Hi Joao,
Have you tried running Python modules with  `-m` option? For example, `python -m src.demo_retrieval`?

**Comment by joao-luz** [comment]
Yes, I had tried that but ran into some local problems.. I spent some time fixing my python installation and it ended up working. Marking it as closed
